server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://ai-photo-editor-hbng.onrender.com/;
        proxy_set_header Host ai-photo-editor-hbng.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
        client_max_body_size 20M;
    }
}